=== Akshita5555/All-My-Projects/WT/program  5/students.dtd
<!ELEMENT students (studentdata+)>
<!ELEMENT student (name, age, course, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT class (#PCDATA)>

=== Akshita5555/All-My-Projects/WT/program  5/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<?xml-stylesheet type="text/css" href="style.css"?>
<students>
    <studentdata>
        <name>John Doe</name>
        <roll>123</roll>
        <age>21</age>
        <class>CSE 13</class>
    </studentdata>
    <studentdata>
        <name>Jane Smith</name>
        <roll>234</roll>
        <age>22</age>
        <class>CSE 13</class>
    </studentdata>
    <studentdata>
        <name>Emily Johnson</name>
        <roll>345</roll>
        <age>21</age>
        <class>CSE 13</class>
    </studentdata>
    </students>
